# Generated by Django 5.1 on 2024-08-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="qq.user"
            ),
        ),
    ]
